config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searchs#search'

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
    @comment = BookComment.find(params[:book_id])
    @book = Book.find(params[:book])
    @book_comment = BookComment.new
    # URLへの直リンクを禁止
    if @comment.user != current_user
      # 1つ前のURLへ返す。
      redirect_to request.referer
    end
    @comment.destroy
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<!-- コメント一覧 -->
        <div class="comment-list bt style-2" id="comments">
          <div class="float-wrapper">
            <h2 class="comment-count"><%= book.book_comments.count %>件のコメント</h2>
          </div>
          <ol>
            <% book.book_comments.each do |book_comment| %>
              <li class="comment">
                <div class="comment-body bb">
                  <div class="comment-avatar">
                    <div class="avatar">
                      <%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
                    </div>
                  </div>
                  <div class="comment-text">
                    <div class="comment-author clearfix">
                      <a href="#" class="link-author"><%= book_comment.user.name %></a>
                      <span class="comment-meta">
                        <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
                      </span>
                    </div>
                    <div class="comment-entry">
                      <%= book_comment.comment %>
                    </div>

                    <!-- コメント投稿者のみ削除リンク -->
                    <% if book_comment.user.id == current_user.id %>
                      <%= link_to "削除",book_book_comments_path(book_id: book_comment.id,book: book_comment.book_id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger", remote: true %>
                    <% end %>
                    <!-- ここまで -->

                  </div>
                </div>
              </li>
            <% end %>
          </ol>
        </div>
        <hr>

        <!-- コメントフォーム -->
        <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
          <h3 class="section-title left">
            <span>コメント</span>
          </h3>
        </div>
        <%= form_with(url: book_book_comments_path(book.id), method: :POST, model: [book,book_comment]) do |f| %>
          <div class="row">
            <div class="col-sm-12">
              <%= f.text_area :comment, rows:'5', class:"form-control",placeholder:"コメントをここに" %>
            </div>
          </div>
          <%= f.submit "送信する", class:"btn btn-lg btn-base-1 mt-20 pull-right" %>
        <% end %>
        <!-- ここまで -->

app/views/book_comments/create.js.erb
$("#comments_update_<%= @book.id %>").html('<%= escape_javascript(render("book_comments/comment", {book: @book, book_comment: @comment})) %>');
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments_update_<%= @book.id %>").html("<%= escape_javascript(render('book_comments/comment', book: @book, book_comment: @book_comment)) %>");