config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searchs#search'

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # ---フォロー機能---
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  # フォロー取得
  has_many :followings, through: :following_relationships
  # 自分がフォローしている人
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  # フォロワー取得
  has_many :followers, through: :follower_relationships
  # 自分がフォローされている人
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  # ---ここまで---

  # prefecture_codeからprefecture_nameに変換するメソッドを定義
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  # ここまで

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image ,:postcode, :prefecture_code, :address_city, :address_street, :latitude, :longitude)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

			<tr>
				<th>follows</th>
				<th><%= link_to "#{user.followings.count}", following_user_path(user) %></th>
			</tr>

			<tr>
				<th>followers</th>
				<th><%= link_to "#{user.followers.count}", followers_user_path(user) %></th>
			</tr>
</table>

<!-- Editボタン(自分のみ表示) -->
<% if user.id == current_user.id %>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

<!-- フォローボタン(自分以外表示) -->
<% unless current_user?(user) %>
	<!-- 現在ログインしているユーザーのプロフィールは、フォロー、フォロー解除のボタンが出ないようにする。 -->
	<div class="row" id="follow_form">
		<% if current_user.following?(user) %>
			<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: {method: :delete}) do |f| %>
				<%= f.submit "フォロー外す", class: "col-xs-12 btn btn-primary" %>
			<% end %>
		<% else %>
			<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
				<div><%= f.hidden_field :following_id %></div>
				<%= f.submit "フォローする", class: "col-xs-12 btn btn-success" %>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<h2>User info</h2>

		<%= form_for(@user) do |f| %>

		<!-- エラーメッセージ表示-->
		<% if @user.errors.any? %>
			<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<!-- エラーメッセージ表示-->

		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name, class: "name" %>
		</div>

		<div class="field">
			<%= f.label :image %>
			<%= f.attachment_field :profile_image, class: "user_image" %>
		</div>

		<div class="field">
			<%= f.label :introduction %>
			<%= f.text_area :introduction, class: "introduction" %>
		</div>

		<div class="actions">
			<%= f.submit %>
		</div>

		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>


		</div>
		<!--users一覧 -->
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>


						<td><%= "フォロー数：#{user.followings.count}" %></td>
						<td><%= "フォロワー数：#{user.followers.count}" %></td>

						<td>
							<% unless current_user?(user) %>
	              <% if current_user.following?(user) %>
	                <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: {method: :delete}) do |f| %>
	                  <%= f.submit "フォロー外す", class: "btn btn-primary" %>
	                <% end %>
	              <% else %>
	                <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
	                  <div><%= f.hidden_field :following_id %></div>
	                      <%= f.submit "フォローする", class: "btn btn-success" %>
	                <% end %>
	              <% end %>
	            <% end %>
	          </td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可 -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>

						<!-- コメント数 -->
						<td>
							<%= "コメント数：#{book.book_comments.count}" %>
						</td>
						<!-- ここまで -->

					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
		<!--ここまで-->

		<!-- Googlemap -->

		<!-- ここまで -->
	<div class="row">
		<% if @user == current_user %>
  <h2>Your MAP</h2>
  <div id='map' class="<%= @user.address_city + @user.address_street %>"></div>
<% end %>
<style>
#map{
  height: 400px;
}
</style>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/

let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()
  geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 8
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <h2>Follow Users</h2>
    <% if @users.count > 0 %>
      <table class="table table-hover">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
              <td><%= user.name%></td>
              <td><%= "フォロー数：#{user.followings.count}" %></td>
              <td><%= "フォロワー数：#{user.followers.count}" %></td>
              <td>
                <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: {method: :delete}) do |f| %>
                  <%= f.submit "フォロー外す", class: "btn btn-primary" %>
                <% end %>
              </td>
              <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    <% else %>
    <p>ユーザーはいません</p>
    <% end %>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="container">
  <div class="row">
    <h2>Follower Users</h2>
    <% if @users.count > 0 %>
      <table class="table table-hover">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
              <td><%= user.name%></td>
              <td><%= "フォロー数：#{user.followings.count}" %></td>
              <td><%= "フォロワー数：#{user.followers.count}" %></td>
              <td>
                <% if current_user.following?(user) %>
                  <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: {method: :delete}) do |f| %>
                    <%= f.submit "フォロー外す", class: "btn btn-primary" %>
                  <% end %>
                <% else %>
                  <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
                    <div><%= f.hidden_field :following_id %></div>
                        <%= f.submit "フォローする", class: "btn btn-success" %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    <% else %>
    <p>ユーザーはいません</p>
    <% end %>
  </div>
</div>