config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searchs#search'

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

# class_name: ‘User’ と補足設定することで、
# Followクラスという存在しないクラスを参照することを防ぎ、
# User クラスであることを明示しています。
# 要は「followモデルなんて存在しないので、
# userモデルにbelongs_toしてね！」って事です。

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # ---フォロー機能---
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  # フォロー取得
  has_many :followings, through: :following_relationships
  # 自分がフォローしている人
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  # フォロワー取得
  has_many :followers, through: :follower_relationships
  # 自分がフォローされている人
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  # ---ここまで---

  # prefecture_codeからprefecture_nameに変換するメソッドを定義
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  # ここまで

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  # sign in後のredirect先変更
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :postcode, :prefecture_name, :address_city, :address_street, :latitude, :longitude])
    #sign_upの際にnameのデータ操作を許可。追加したカラム。
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    # ログイン時にnameを使用
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
  	@books = Book.find(params[:id])
    @book = Book.new
    @user = @books.user
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id=current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how,@model,@content)
  end

  private
  def match(model,content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model,content)
    if model == 'user'
      User.where("name LIKE ?", "#{content}%")
    elsif model == 'book'
      Book.where("title LIKE?", "#{content}%")
    end
  end

  def backward(model,content)
    if model =='user'
      User.where("name LIKE?", "%#{content}")
    elsif model == 'book'
      Book.where("title LIKE?", "%#{content}")
    end
  end

  def partical(model,content)
    if model == 'user'
      User.where("name LIKE?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE?", "%#{content}%")
    end
  end

    def search_for(how,model,content)
      case how
      when 'match'
        match(model,content)
      when 'forward'
        forward(model,content)
      when 'backward'
        backward(model,content)
      when 'partical'
        partical(model,content)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image ,:postcode, :prefecture_code, :address_city, :address_street, :latitude, :longitude)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->

    <!-- 検索機能 -->
    <% if user_signed_in? %>
      <div class="container">
        <div class="row search-form">
          <div class="col-xs-9 col-xs-offset-3">
            <%= form_tag(search_path, method: :get) do %>
              <%= text_field_tag 'search[content]' %>
              <%= select_tag 'search[model]', options_for_select({"User" => "user", "Book" => "book"}) %>
              <%= select_tag 'search[how]', options_for_select({"完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"}) %>
              <%= submit_tag '検索',class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    </div>
    <%= yield %>
  </body>
</html>